# WildFly Operator for Kubernetes/OpenShift

The WildFly Operator for Kubernetes provides easy monitoring and configuration for Java applications deployed on http://wildfly.org[WildFly application server].

Once installed, the WildFly Operator provides the following features:

* Create/Destroy: Easily launch an application deployed on WildFly

* Simple Configuration: Configure the fundamentals of WildFly-based application including number of nodes, application image, etc.

## Custom Resource Definitions

The operator acts on the following Custom Resource Definitions (CRDs):

* `WildFlyServer`, which defines a WildFly deployment. The `Spec` and `Status` of this resources are defined in the https://github.com/jmesnil/wildfly-operator/blob/master/doc/apis.adoc[API documentation].

## Quickstart

### Install the Operator and associate resources:

The examples require that https://kubernetes.io/docs/setup/minikube/[Minikube] is installed and running.

[source,shell]
----
# Install resource for the WildFly Operator
$ kubectl create -f deploy/service_account.yaml
$ kubectl create -f deploy/role.yaml
$ kubectl create -f deploy/role_binding.yaml

# install the WildFlyServer CRD that the Operator manages
$ kubectl create -f deploy/crds/wildfly_v1alpha1_wildflyserver_crd.yaml

# install WildFly Operator
$ kubectl create -f deploy/operator.yaml
----

### Install a custom resource

An example of a custom resource of `WildFlyServer` is described in http://deploy/crds/wildfly_v1alpha1_wildflyserver_cr.yaml[wildfly_v1alpha1_wildflyserver_cr.yaml]:

[source,yaml]
----
apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: myapp-wildflyserver
spec:
  applicationImage: "quay.io/jmesnil/wildfly-helloworld-rs:16.0.0.Final"
  stateful: true
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 3Gi
----

[NOTE]
=====
It is based on the application image https://quay.io/repository/jmesnil/wildfly-operator-quickstart[jmesnil/wildfly-operator-quickstart] that provides a simple Java Web application https://github.com/jmesnil/wildfly-operator-quickstart[wildfly-operator-quickstart] on top of WildFly 16.0.0.Final which returns the IP address of its host:

[source,shell]
----
$ curl http://localhost:8080/
{"ip":"172.17.0.3"}
----

This simple application illustrates that successive calls will be load balanced across the various pods that runs the application
=====

[source,shell]
----
$ kubectl create -f deploy/crds/wildfly_v1alpha1_wildflyserver_cr.yaml

wildflyserver.wildfly.org "myapp-wildflyserver" created
----

Once the application is deployed, it can be accessed through a load balancer:

[source,shell]
----
$ curl $(minikube service myapp-wildflyserver-loadbalancer --url)
{"ip":"172.17.0.9"}
$ curl $(minikube service myapp-wildflyserver-loadbalancer --url)
{"ip":"172.17.0.10"}
$ curl $(minikube service myapp-wildflyserver-loadbalancer --url)
{"ip":"172.17.0.11"}
----

As illustrated above, calls to the application are load balanced across the pods that runs the application image (as we can see from the different IP addresses).

The WildFly operator describes the deployed application with `$ kubectl describe wildflyserver myapp-wildflyserver`:

[source,yaml]
----
kubectl describe wildflyserver
Name:         myapp-wildflyserver
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  wildfly.org/v1alpha1
Kind:         WildFlyServer
Metadata:
  Creation Timestamp:  2019-03-11T17:25:25Z
  Generation:          1
  Resource Version:    330444
  Self Link:           /apis/wildfly.org/v1alpha1/namespaces/default/wildflyservers/myapp-wildflyserver
  UID:                 a88933a0-4422-11e9-a9e2-ee8c8192f3c7
Spec:
  Application Image:  quay.io/jmesnil/wildfly-helloworld-rs:16.0.0.Final
  Size:               3
  Storage:
    Volume Claim Template:
      Spec:
        Resources:
          Requests:
            Storage:  3Gi
Status:
  Nodes:
    myapp-wildflyserver-0
    myapp-wildflyserver-1
    myapp-wildflyserver-2
Events:  <none>
----

The `Status` section is updated with the 3 pods names containing the application image.

You can modify this custom resource spec to scale down its size from `3` to `2`:

[source,shell]
----
$ kubectl edit wildflyserver myapp-wildflyserver
# Change the `size: 3` spec to `size: 2` and save
----

The deployment will be updated to scale down to 2 Pods and the resource `Status` will be updated accordingly:

[source,shell]
----
$ kubectl describe wildflyserver myapp-wildflyserver
----

[source,yaml]
----
Name:         myapp-wildflyserver
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  wildfly.org/v1alpha1
Kind:         WildFlyServer
Metadata:
  Creation Timestamp:  2019-03-18T11:17:02Z
  Generation:          2
  Resource Version:    2704
  Self Link:           /apis/wildfly.org/v1alpha1/namespaces/default/wildflyservers/myapp-wildflyserver
  UID:                 5b103c16-496f-11e9-83fc-2ec30bcb3dcf
Spec:
  Application Image:  quay.io/jmesnil/wildfly-helloworld-rs:16.0.0.Final
  Size:               2
  Storage:
    Volume Claim Template:
      Spec:
        Resources:
          Requests:
            Storage:  3Gi
Status:
  Nodes:
    myapp-wildflyserver-0
    myapp-wildflyserver-1
Events:  <none>
----

You can then remove this custom resource and its assocated resources:

[source,shell]
----
$ kubectl delete wildflyserver myapp-wildflyserver

wildflyserver.wildfly.org "myapp-wildflyserver" deleted
----

#### OpenShift

The examples can also be installed in OpenShift and requires a few additional steps.

The instructions requires that https://github.com/minishift/minishift[Minishift] is installed and running.

Before deploying the operator and its resources, execute the following commands:

[source,shell]
----
$ oc login -u system:admin
$ oc adm policy add-cluster-role-to-user cluster-admin developer

$ oc login -u developer
$ oc project myproject
$ oc adm policy add-scc-to-user privileged -n myproject -z wildfly-operator
$ oc adm policy add-scc-to-user privileged -n myproject -z wildflyserver
----

After installing the `WildFlyServer` resource from `deploy/crds/wildfly_v1alpha1_wildflyserver_cr.yaml`, you have to create a route to expose it from OpenShift:

[source,shell]
----
$ oc expose svc/myapp-wildflyserver-loadbalancer
----

This will expose the service from OpenShift. To know the URL of the exposed service, run:

[source,shell]
----
$ oc get route myapp-wildflyserver-loadbalancer --template='{{ .spec.host }}'
----

This will display the host of the route (on my local machin, it displays `myapp-wildflyserver-loadbalancer-myproject.192.168.64.11.nip.io`).

The application can then be accessed by running:

[source,shell]
----
$ curl "http://$(oc get route myapp-wildflyserver-loadbalancer --template='{{ .spec.host }}')"
{"ip":"172.17.0.9"}
----
