# JAX-RS + PostgreSQL application

This example shows how to install and deploy a JAX-RS application that uses a PostgreSQL database on OpenShift using the WildFly Operator.

## Prerequisites

* Install OpenShift (or minishift)
* Deploy a PostgreSQL template from the Catalog and keep the default values:

----
Username: <generated content>
Password: <generated content>
Database Name: sampledb
Connection URL: postgresql://postgresql:5432/
----

* The application will get the database credentials from the secret created by the PostgreSQL template:

[source,shell]
----
$ oc describe secret postgresql
Name:         postgresql
Namespace:    myproject
...

Type:  Opaque

Data
====
database-user:      7 bytes
database-name:      8 bytes
database-password:  16 bytes
----

* Install the WildFly Operator as explained in the https://github.com/wildfly/wildfly-operator#install-the-operator-and-associate-resources[README].

# Deploy the application

The application is defined in the https://github.com/wildfly/wildfly-operator/blob/master/examples/tasksrs/crds/taskrs-app.yaml[taksrs-app.yaml file]:

[source,yaml]
----
apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: taskrs-app
spec:
  applicationImage: "quay.io/jmesnil/taskrs-app:17.0"
  size: 2
  env:
  - name: POSTGRESQL_SERVICE_HOST
    value: postgresql
  - name: POSTGRESQL_SERVICE_PORT
    value: '5432'
  - name: POSTGRESQL_DATABASE
    valueFrom:
      secretKeyRef:
        key: database-name
        name: postgresql
  - name: POSTGRESQL_USER
    valueFrom:
      secretKeyRef:
        key: database-user
        name: postgresql
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-password
        name: postgresql
----

This custom resource will run the https://github.com/jfdenise/s2i-wildfly/tree/master/17.0/test/test-app-postgres[test-app-postgres] application from the https://quay.io/repository/jmesnil/taskrs-app[quay.io/jmesnil/taskrs-app:17.0] image that is using the https://github.com/wildfly/wildfly-s2i[Source-to-Image (S2I) template for WildFly].

The application requires the following Environment variables to configure its connection to PostgreSQL:

* `POSTGRESQL_SERVICE_HOST` : `postgresql`
* `POSTGRESQL_SERVICE_PORT` : `5432`
* `POSTGRESQL_USER` : the value is read from the `database-user` key from the `postgresql` secret
* `POSTGRESQL_PASSWORD` : the value is read from the `database-password` key from the `postgresql` secret
* `POSTGRESQL_DATABASE` : the value is read from the `database-name` key from the `postgresql` secret

The application will have 2 instances running behind its load balancer.

[source,shell]
----
$ oc apply -f crds/taskrs-app.yaml
wildflyserver.wildfly.org/taskrs-app created
----

You can then check the status of the application:

[source,shell]
----
$ oc describe wildflyserver taskrs-app
Name:         taskrs-app
Namespace:    myproject
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"wildfly.org/v1alpha1","kind":"WildFlyServer","metadata":{"annotations":{},"name":"taskrs-app","namespace":"myproject"},"spec":{"applicat...
API Version:  wildfly.org/v1alpha1
Kind:         WildFlyServer
Metadata:
  Cluster Name:
  Creation Timestamp:  2019-04-01T21:42:43Z
  Finalizers:
  Generation:  1
  Owner References:
  Resource Version:  188525
  Self Link:         /apis/wildfly.org/v1alpha1/namespaces/myproject/wildflyservers/taskrs-app
  UID:               14c880f3-54c7-11e9-9fb5-065375b5f883
Spec:
  Application Image:  quay.io/jmesnil/taskrs-app:17.0
  Env:
    Name:   POSTGRESQL_SERVICE_HOST
    Value:  postgresql
    Name:   POSTGRESQL_SERVICE_PORT
    Value:  5432
    Name:   POSTGRESQL_DATABASE
    Value From:
      Secret Key Ref:
        Key:   database-name
        Name:  postgresql
    Name:      POSTGRESQL_USER
    Value From:
      Secret Key Ref:
        Key:   database-user
        Name:  postgresql
    Name:      POSTGRESQL_PASSWORD
    Value From:
      Secret Key Ref:
        Key:   database-password
        Name:  postgresql
  Size:        2
Status:
  Hosts:
    taskrs-app-myproject.192.168.64.32.nip.io
  Pods:
    Name:    taskrs-app-0
    Pod IP:  172.17.0.5
    Name:    taskrs-app-1
    Pod IP:  172.17.0.9
Events:      <none>
----

The operator will also create a loadbalancer and a HTTP route to expose the application:

[source,shell]
----
$ oc get service taskrs-app-loadbalancer
NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP                     PORT(S)          AGE
taskrs-app-loadbalancer   LoadBalancer   172.30.196.165   172.29.120.211,172.29.120.211   8080:31771/TCP   10h

$ oc get route taskrs-app
NAME         HOST/PORT                                   PATH      SERVICES                  PORT      TERMINATION   WILDCARD
taskrs-app   taskrs-app-myproject.192.168.64.32.nip.io             taskrs-app-loadbalancer   http                    None
----

The external address can be found by running: 

[source,shell]
----
$ oc get route taskrs-app --template='{{ .spec.host }}'
taskrs-app-myproject.192.168.64.32.nip.io
----

The application will display a list of tasks (in XML):

[source,shell]
----
$ curl "http://$(oc get route taskrs-app --template='{{ .spec.host }}')"
----

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<collection/>
----

We can then add tasks by POSTing to the application:

[source,shell]
----
curl -i  -H "Content-Length: 0" -X POST "http://$(oc get route taskrs-app --template='{{ .spec.host }}')/tasks/title/my%20first%20task"

HTTP/1.1 201 Created
...
----

If we go again to the application URL, we see that a task has been added and persisted to PostgreSQL:

[source,xml]
----
<collection>
  <task id="1" ownerName="Anonymous">
    <title>my first task</title>
  </task>
</collection>
----


