apiVersion: wildfly.org/v1alpha2
kind: WildFlyServer
metadata:
  name: quickstart
spec:
  applicationImage: "quay.io/wildfly-quickstarts/wildfly-operator-quickstart:18.0"
  replicas: 2
  configMaps:
    - name: extensions-configmap
      mountPath: extensions
