apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "wildfly.org/v1alpha1",
          "kind": "WildFlyServer",
          "metadata": {
            "name": "quickstart-v1alpha1"
          },
          "spec": {
            "applicationImage": "quay.io/wildfly-quickstarts/wildfly-operator-quickstart:18.0",
            "configMaps": [
              "extensions-configmap"
            ],
            "replicas": 2
          }
        },
        {
          "apiVersion": "wildfly.org/v1alpha2",
          "kind": "WildFlyServer",
          "metadata": {
            "name": "quickstart"
          },
          "spec": {
            "applicationImage": "quay.io/wildfly-quickstarts/wildfly-operator-quickstart:18.0",
            "configMaps": [
              {
                "mountPath": "extensions",
                "name": "extensions-configmap"
              }
            ],
            "replicas": 2
          }
        }
      ]
    capabilities: Basic Install
  name: wildfly-operator.v0.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: WildFlyServer is the Schema for the wildflyservers API
      kind: WildFlyServer
      name: wildflyservers.wildfly.org
      version: v1alpha2
    - description: WildFlyServer is the Schema for the wildflyservers API
      kind: WildFlyServer
      name: wildflyservers.wildfly.org
      version: v1alpha1
  description: An application running on WildFly application runtime.
  displayName: WildFlyServer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - update
        serviceAccountName: wildfly-operator
      deployments:
      - name: wildfly-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: wildfly-operator
          strategy: {}
          template:
            metadata:
              labels:
                app: wildfly-operator
                name: wildfly-operator
            spec:
              containers:
              - args:
                - --zap-level=5
                - --zap-encoder=console
                command:
                - wildfly-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: wildfly-operator
                image: quay.io/yborgess/wildfly-operator-dev:0.5.0
                imagePullPolicy: Always
                name: wildfly-operator
                ports:
                - containerPort: 8443
                resources: {}
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: vol-webhook-certs
                  readOnly: true
              serviceAccountName: wildfly-operator
              volumes:
              - name: vol-webhook-certs
                secret:
                  secretName: webhook-certs
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/exec
          - pods/log
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - deployments/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - wildfly.org
          resources:
          - '*'
          - wildflyservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: wildfly-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - wildfly
  links:
  - name: Wildfly Operator
    url: https://wildfly-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.5.0
